{% set version = "1.2.0" %}

package:
  name: libtheora
  version: {{ version }}

source:
  url: https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-{{ version }}.tar.gz
  sha256: 279327339903b544c28a92aeada7d0dcfd0397b59c2f368cc698ac56f515906e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libtheora', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool   # [unix]
    - make      # [unix]
    - autotools_clang_conda  # [win]
  host:
    - libogg
    - libvorbis

test:
  commands:
    # Verify libraries.
    {% set libtheora_libs = [
        "theora",
        "theoradec",
        "theoraenc"
    ] %}
    {% for each_libtheora_lib in libtheora_libs %}
    # Static libraries should not exists, see https://github.com/conda-forge/cfep/blob/main/cfep-18.md
    - test ! -f ${PREFIX}/lib/lib{{ each_libtheora_lib }}.a                           # [unix]
    - test -f ${PREFIX}/lib/lib{{ each_libtheora_lib }}.dylib                       # [osx]
    - test -f ${PREFIX}/lib/lib{{ each_libtheora_lib }}.so                          # [linux]
    - if exist %PREFIX%\\Library\\lib\\{{ each_libtheora_lib }}.lib (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\include\\{{ each_libtheora_lib }}.h (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\{{ each_libtheora_lib }}.dll (exit 0) else (exit 1)  # [win]
    {% endfor %}


about:
  home: https://theora.org
  license: BSD-3-Clause
  # BSD like
  license_family: BSD
  # Additional licencing information in LICENSE as well
  license_file: COPYING
  summary: "Theora is a free and open video compression format from the Xiph.org Foundation."

extra:
  recipe-maintainers:
    - bgruening
    - dschreij
    - traversaro
