appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IDwEjFT+9A0FZIpSWU1mvV6AMS5TolfT1MYnQz0JgMEvCvLUhWam1YSy3p3wf+GdwVFnpKs56Lje9X+lhsr15DXvwc084xrvxTxToy5nRQnm71wCoqA3jH4zWZUGdC2ivfn9bb6h3pb0+6Vq4qE2nweijXWZrRttJUbI3vSakr37AFDPi8aszqTQz12NLNHZgdOfAEXpflEEKUxpOJO/iuRCSoVh9qPp31NjF2Lt74QbmIBFeeRaJrB64hWrpT7KK5tBogX3ehkqZCOFr4MtEH0cptTaWPukgnC//2o1pmSyvlSgs38kY3oBDYblANPGSLlRFbU8pvupiYFxEqi/75Cz6sqDiqCw6ez08jDOxg49433vgjNN3SBeWj0ordpXxhz/aTGpiXDAG1S7uz5yfbY0gJttJAA54jDC7D0m8zhZaAKCJuRukP7u8pDt0HZQpHLt7I6pm9EGKISQDLO0nILRX6E2NyHsVwWsMtaeld4sMOsS7x3oP161P9mxTysFkPDnSbi1tWqzSYjO1lZQfk13pLki9l+MbH+3D3dVHAK9MjFxB03zk7ne70mxR3SuxSBIC+RNaeBJgofn1pBQahOk49j0+WseMP01cwyF8CoSQFJPazXAjRmNFrCtIDYhB3isfSEc4673nVW/NIXKlouoZMhDE2ewoDEnzrTKWio=}
